title: Indian Statistical Institute Academic Calendar
description: Academic Calendar Website for ISI, 2nd Semester 2025â€“2026
baseurl: "/isi-sansani" 
url: "https://gouthamsaipydi.github.io" 
markdown: kramdown
theme: minima

author:
  name: "Goutham Sai Pydi"
  email: "saigouthampydi@gmail.com"

plugins:
  - jekyll-feed